name: aldrin
description: Single Page Applications running on the server side.
version: 0.1.0
repository: https://github.com/infodusha/aldrin

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  nanoid: ^1.0.0
  args: ^2.3.1
  hotreloader: ^3.0.4
  intl: ^0.17.0
  tuple: ^2.0.0
  rxdart: ^0.27.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  aldrin:
